//
//  Excerpts.swift
//  Brass Excerpts
//
//  Created by Thomas Swatland on 03/12/2017.
//  Copyright © 2017 Thomas Swatland. All rights reserved.
//

import Foundation

struct Excerpt {
    let composer: String
    let firstName: String
    let pieces: [String]
}

let trumpetExcerpts: [Excerpt] = [Excerpt(composer: "Bach",
                                        firstName: "Johann Sebastian",
                                        pieces: ["Brandenburg Concerto no.2",
                                                "Christmas Oratorio",
                                                "Magnificat",
                                                "Mass in b minor"]),
                               Excerpt(composer: "Beethoven",
                                        firstName: "Ludwig van",
                                        pieces: ["Leonore Overture no. 2",
                                                "Symphony no. 9"]),
                               Excerpt(composer: "Bizet",
                                        firstName: "Georges",
                                        pieces: ["Carmen"]),
                               Excerpt(composer: "Brahms",
                                        firstName: "Johannes",
                                        pieces: ["Academic Festival Overture",
                                                "Symphony no. 2"]),
                               Excerpt(composer: "Bruckner",
                                        firstName: "Anton",
                                        pieces: ["Symphony no. 7",
                                                "Symphony no. 8"]),
                               Excerpt(composer: "Donizetti",
                                        firstName: "Gaetano",
                                        pieces: ["Don Pasquale"]),
                               Excerpt(composer: "Dvorak",
                                        firstName: "Antonin",
                                        pieces: ["Symphony no. 8"]),
                               Excerpt(composer: "Mahler",
                                        firstName: "Gustav",
                                        pieces: ["Symphony no. 3",
                                                "Symphony no. 5",
                                                "Symphony no. 9"]),
                               Excerpt(composer: "Mussorgsky",
                                        firstName: "Modest",
                                        pieces: ["Pictures at an Exhibition"]),
                               Excerpt(composer: "Ravel",
                                        firstName: "Maurice",
                                        pieces: ["Piano Concerto"]),
                               Excerpt(composer: "Rimsky-Korsakov",
                                        firstName: "Nikolai",
                                        pieces: ["Scheherazade"]),
                               Excerpt(composer: "Tchaikovsky",
                                        firstName: "Pyotr Ilych",
                                        pieces: ["The Nutcracker",
                                                "Swan Lake",
                                                "Symphony no. 4",
                                                "Symphony no. 5"]),
                               Excerpt(composer: "Wagner",
                                        firstName: "Richard",
                                        pieces: ["Parsifal",
                                                "Tannhauser"])]

let tromboneExcerpts: [Excerpt] = [Excerpt(composer: "Beethoven",
                                        firstName: "Ludwig van",
                                        pieces: ["Fidelio Overture",
                                                "Symphony no. 5",
                                                "Symphony no. 9"]),
                               Excerpt(composer: "Berlioz",
                                        firstName: "Hector",
                                        pieces: ["Hungarian March",
                                                "Roman Carnival Overture",
                                                "Symphonie Fantastique"]),
                               Excerpt(composer: "Brahms",
                                        firstName: "Johannes",
                                        pieces: ["Academic Festival Overture",
                                                "Symphony no. 1",
                                                "Symphony no. 2",
                                                "Symphony no. 3",
                                                "Symphony no. 4"]),
                               Excerpt(composer: "Mahler",
                                        firstName: "Gustav",
                                        pieces: ["Symphony no. 3",
                                                "Symphony no. 5"]),
                               Excerpt(composer: "Mozart",
                                        firstName: "Wolfgang Amadeus",
                                        pieces: ["Requiem"]),
                               Excerpt(composer: "Ravel",
                                        firstName: "Maurice",
                                        pieces: ["Bolero"]),
                               Excerpt(composer: "Rossini",
                                        firstName: "Gioachino",
                                        pieces: ["La Gazza Ladra",
                                                "William Tell Overture"]),
                               Excerpt(composer: "Saint-Saens",
                                        firstName: "Camille",
                                        pieces: ["Symphony no. 3 Organ"]),
                               Excerpt(composer: "Schumann",
                                        firstName: "Robert",
                                        pieces: ["Symphony no. 3 Rhenish"]),
                               Excerpt(composer: "Wagner",
                                        firstName: "Richard",
                                        pieces: ["Lohengrin act 3",
                                                "Ride of the Valkyries",
                                                "Tannhauser Overture"])]

let tubaExcerpts: [Excerpt] = [Excerpt(composer: "Berlioz",
                                        firstName: "Hector",
                                        pieces: ["Hungarian March",
                                                "Symphonie Fantastique"]),
                               Excerpt(composer: "Brahms",
                                        firstName: "Johannes",
                                        pieces: ["Academic Festival Overture",
                                                "Symphony no. 2"]),
                               Excerpt(composer: "Bruckner",
                                        firstName: "Anton",
                                        pieces: ["Symphony no. 4",
                                                "Symphony no. 7"]),
                               Excerpt(composer: "Mahler",
                                        firstName: "Gustav",
                                        pieces: ["Symphony no. 1",
                                                "Symphony no. 5"]),
                               Excerpt(composer: "Mendelssohn Bartholdy",
                                        firstName: "Felix",
                                        pieces: ["A Midsummer Night's Dream"]),
                               Excerpt(composer: "Mussorgsky",
                                        firstName: "Modest",
                                        pieces: ["Pictures at an Exhibition"]),
                               Excerpt(composer: "Respighi",
                                        firstName: "Ottorino",
                                        pieces: ["Fountains of Rome"]),
                               Excerpt(composer: "Wagner",
                                        firstName: "Richard",
                                        pieces: ["Das Rheingold",
                                                "Die Meistersinger von Nurnburg",
                                                "Ride of the Valkyries"])]

